### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [julianlehr/firehose_splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by julianlehr** [comment]
Ha! Good feedback! 
I only checked responsiveness by resizing my browser window - not on an actual phone.

I just added this to the <head> in my application.html.erb file - seems to be working now:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

(Did I miss this step in one of the lessons or did leave it out on purpose? 🤔)

**Comment by BillyMassey** [comment]
Nope! It's just some additional feedback I had for the app outside the lessons 😃 
Great job looking it up and implementing it though!
